### ISSUE TITLE
Using national num shaping throws an error 

### ISSUE THREAD

**Issue by manigurusankar10** [wajnberg/national-flatpickr#1]
When typeNumShaping is`National` it throws the following error.

![Screen Shot 2021-04-13 at 9 58 48 AM](https://user-images.githubusercontent.com/18562377/114575028-68335780-9c3f-11eb-8ef0-f9d95f9935fe.png)

## Your Environment

* flatpickr version used: latest
* Browser name and version: Chrome 89.0.4389.114
* OS and version: Mac OS 11.2.3

**Comment by wajnberg** [comment]
Hello @manigurusankar10 

I made a fix for this issue. Could you please try again ?

Thank you
